[theme]
primaryColor = "#F37B1F"          # Orange (Boutons, Sliders)
backgroundColor = "#0D0B50"       # Fond sombre
secondaryBackgroundColor = "#161D6F" # Barre latérale
textColor = "#E5E5E5"             # Texte général
font = "sans serif"